version: "3"

volumes:
  src:
  db:

services:
  laravelreact_db:
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: laravel
    ports:
      - "8081:3306"
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    hostname: db

  dbadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    ports:
      - 8082:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: laravelreact_db
    hostname: dbadmin

  web:
    build:
      context: ./dockerfiles
    ports:
      - "8080:80"
      - "3000:3000"
    volumes:
      - type: volume
        source: src
        target: /var/www/html
    hostname: web
    privileged: true
